
CREATE TABLE STUDENT (
    SNO VARCHAR2(3 BYTE) NOT NULL ,
    SNAME VARCHAR2(9 BYTE) NOT NULL ,
    SSEX CHAR(2 BYTE) NOT NULL
);
INSERT INTO STUDENT VALUES ('1', 'NAMEA', 'M ');
INSERT INTO STUDENT VALUES ('2', 'NAMEB', 'M ');
INSERT INTO STUDENT VALUES ('3', 'NAMEC', 'F ');